### ISSUE TITLE
Не все планые повороты подсказываются

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#1]
При навигации на местности при плавном повороте устройство дает подсказку "идите прямо", вместо "поверните".

**Comment by patut** [comment]
На данный момент, почему это не реализовано: нужен алгоритм выбора ближайших точек из объекта polyline (каждого шага). Он есть в теории, сейчас нужно написать функцию, которая будет выбирать точку по направлению движения пользователя, чтобы правильно строить вектор

**Comment by Philat** [comment]
Сколько займет по времени и когда можно будет посмотреть?

**Comment by patut** [comment]
Написание функции - минут 30, не больше. Посл написания функции, необходимо написать еще одну, которая будет определять сторону, в которую нужно повернуть в зависимости от косинуса угла и еще чего-то

**Comment by Philat** [comment]
Я не понимаю во сколько это будет готово
Когда я смогу на это посмотреть, чтобы оно работало так как надо, хотя бы в первом приблежении
напиши дату, месяц, точное время

**Comment by patut** [comment]
В 14-00 будет готово следующее: вывод в консоль косинуса угла между двумя векторами и вывод того, в какую сторону осуществляется плавный поворот (вправо-влево)

**Comment by patut** [comment]
На данный момент сделал выборку оптимальной точки, в консоль выводится угол между двумя векторами в градусах. Но пока все считается неправильно (скорее всего ошибка в алгоритме)

**Comment by patut** [comment]
для определения, куда нужно поворачивать (направо или налево) нужно придумать алгоритм, пока думаю над этим

**Comment by patut** [comment]
Нашел такую формулу atan2(V2.Y,V2.X)-atan2(V1.Y,V1.X). Буду пробовать

**Comment by patut** [comment]
Сделал вывод угла поворота и определение того, в какую сторону поворачивать (зависит от знака значения угла).

**Comment by patut** [comment]
я кажется понял, почему неправильно строит вектор. Причина: пользователь идет не по дороге, а около нее. Добавлю новый алгоритм

**Comment by patut** [comment]
Подсказки работают по новому алгоритму, пока неправильному(

**Comment by patut** [comment]
сделал вывод в консоль и в title

**Comment by Philat** [comment]
Приложение скрин как выводит и в какой формате

**Comment by Philat** [comment]
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by patut** [comment]
[Cсылка на скрины] https://drive.google.com/drive/#folders/0B75a4hhDNsEVVEZTUlNqYU84U1E/0B75a4hhDNsEVUHAzMXNiZVBsaUk/0B2cN1ZH8gt52fktTNC1NaGpXTzlhN3Y2dkpqaDlaSG1pTkI1MF83WlJQSFVTa1FQck9jSWM

**Comment by Philat** [comment]
https://drive.google.com/open?id=0B2cN1ZH8gt52SW1iaHlvakxJbFE&authuser=0
https://drive.google.com/open?id=0B2cN1ZH8gt52YWRmLVVFN3NFbDg&authuser=0
