### ISSUE TITLE
Урезать карту, добавить текстовое поле с окрестностями (для дерзких)

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#12]
При определении местоположения выводить ниже в текстовое поле список домов вокруг текущего местоположения, достопримечательности, улицы и перекрестки, если таковые есть. 
желательно в формате - 

дом 32  Тверская - 2 часа
Поворот на Андропова - 3 часа
дом 36 Тверская - 5 часов
перекресток - 9 часов
памятник Пушкина - 11 часов

Если не удастся понять где именно находится пользователей из-за неточности геолакации то прямо вывести сообщение 
вы находитесь в районе улиц Тверская Большая бронная  малая бронная, вы ищете иль Патио по адресу Малая бронная д 34. Уточните дорогу у прохожих. Обратитесь к системе чуть позже. 

а в тайтле при этом где  "налево-направо"
"Мы устанавливаем ваше местоположение"

**Comment by patut** [comment]
Сделал вывод в label (сверху карты) список ближайших мест.

https://drive.google.com/open?id=0B2cN1ZH8gt52LVlvd0JOQ2RnN0k&authuser=0

**Comment by Philat** [comment]
лейбл выводится на русском?

**Comment by patut** [comment]
да, в скрине английские названия, потому что купертина

**Comment by patut** [comment]
пофиксил баг с вылетом программы в начале

**Comment by patut** [comment]
пофиксил некоторые вылеты на вью с картой

**Comment by patut** [comment]
Сделал следующую фугкцию: программа называет улицы, на которых возможно находится пользователь

**Comment by patut** [comment]
Сделал практически все задание, кроме вывода углов поворота. Пока выводятся близлежащие улицы, если точность определения маршрута их охватывает. То есть, если приложение определяет пользователя в радиусе 2ух и более улиц, то выводятся все эти улицы с просьбой уточнить местоположение. Баг: выводятся повторяющиеся улицы, он будет устранен в ближайшее время (пока не устранен, потому что нужна была версия xcode 6.3 beta для правильной работы функции).

**Comment by patut** [comment]
Часы поворота пока делать не буду, хочу сосредоточиться на версии для часов, добить эту тему сначала.

**Comment by Philat** [comment]
Сначала углы потом часы
Углы важнее
Приложение на часах без наличия айфона мы не продадим
Айфонов в мире больше чем часов
Сначала телефоны потом часы

Часы это такая площадка которая увеличит нам продажи если основной продукт будет удобен
Если основной продукт будет говно то приложения доя часов никто не скачает

**Comment by patut** [comment]
Сделал.
https://drive.google.com/open?id=0B2cN1ZH8gt52U3lpUmh1Q3lrN2M&authuser=0

**Comment by Philat** [comment]
затестить в поле во время движения

**Comment by patut** [comment]
Затестил во время движения, понял, что лучше прогнать 5 апдейтов локации, а потом только брать 2 точки, потому что перво определение - очень неточное. Так устройство сообщает повороты правильно (по часам).

**Comment by patut** [comment]
Оставил как есть, считаю проблему решенной
