### ISSUE TITLE
30 тестов, глубинное интервью с гиками

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#15]
протестировать продукт на 30 людях, взять интервью

**Comment by Philat** [comment]
1 - никак не могу встреться
завтра обязательно надо сделать
чт в 10 утра

**Comment by Philat** [comment]
Перенесено на следующую итерацию
на данной иттерации необходимо составить список адресов и телефонов

**Comment by patut** [comment]
тестирование будет в субботу с сергеем
