### ISSUE TITLE
Список мест для тестирования

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#19]
https://github.com/WillyTeam/willy/issues/15
связано с этой задачей на следующую итерацию

**Comment by patut** [comment]
Список место создан, теперь будем его дополнять информацией из сарафанного радио (типа как Николай с Логосом и Василий с колл-центром) https://docs.google.com/spreadsheets/d/1YDXSIbdbkkoJ4xRwB3PUrVvBDVXp0svcxgUZkyqFLbk/edit#gid=426850155
