### ISSUE TITLE
Аудиоподсказки не выдаются автоматически

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#2]
При навигации используется технология IPhone voice over, которая прочитывает надписи с экрана.
На данный момент прочитывание не осуществляется автоматически. Приходится постоянно нажимать пальцем.
Необходимо сделать прочитывание подсказки либо раз в какое-то время (автоклик по таймеру), либо прочитывание подсказки при изменении

**Comment by patut** [comment]
Сделал, но нужно проверить работу

**Comment by patut** [comment]
Все работает, подсказывает раз в 4 секунды.
