### ISSUE TITLE
Сайты знакомств

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#22]
Зарегаться на сайтах знакомств и искать аудиторию там
прямо массово всем писать и рассылать

заргеать и себя и меня
Разослать не меньше 200 писем

составить список вопросов на основе требуемых данных для регрессионой модели

**Comment by patut** [comment]
Зарегал только себя: знакомства пока крайне неэффективны, самое полезное, что достал - выход на 2 тематические группы в вк - по 4000 подписчиков. Они запилят наш пост в свою группу

**Comment by Philat** [comment]
суммарно 8000 человек охват?

**Comment by Philat** [comment]
сегодня с меня список органзиация в таске 
https://github.com/WillyTeam/willy/issues/19

**Comment by patut** [comment]
Получается так

**Comment by patut** [comment]
Ну там не очень активные все

**Comment by patut** [comment]
так что меньше

**Comment by patut** [comment]
Сейчас буду ломиться в fb
