### ISSUE TITLE
Составить анкеты для каждой ЦА

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#27]
составить анкеты https://github.com/WillyTeam/willy/issues/26

**Comment by patut** [comment]
Надо ли? вот у меня тут вопрос, потому что можно составить анкету таким образом, чтобы внутри нее определялась ЦА

**Comment by Philat** [comment]
да надо
анкет должно быть все равно больше чем одна
несмотря на то что мы получаем одинаковые выходные данные формулировки вопросов будут отличаться в зависимости от того как группу мы тестируем
можно разделить анкеты по блокам

типа анкета для слепых - там уже дифференцировать их по возрасту и уровню дохода
анкета для слабовидящих
для родственников
для плоховидящих
для аутистов

**Comment by patut** [comment]
Ок, а формулировки каких вопросов должны отличаться?

**Comment by Philat** [comment]
сложно сказать так с потолка
как минимум вопрос "нравится вам или нет" должен быть заменен для каждой целевой аудитории специально для ее проблемы
то есть у слепых проблема то, что они не могут вводит с клавиатуры и они ничего не видят
значит для них пул вопросов типа "те места которые есть норм или нужны какие-то другие категории", "понятно ли куда нажимать", "на улице комфортно - нет", "нужна ли доп информация"
а аутиков например главная проблема интроверсия, значит "те подсказки которые есть помогают дойти до нужного места", "испытывали ли вы потребность в том, чтобы спросить дорогу у прохожих" и прочее
вопросы для каждой группы должны быть сформулированы с точки зрения потребности и основных страхов
у этих больших групп они разные

**Comment by patut** [comment]
Связано с https://github.com/WillyTeam/willy/issues/43
