### ISSUE TITLE
Проводить тесты

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#28]
Всерос общество слепых на Полежаевской
Анкетирование 300 связана https://github.com/WillyTeam/willy/issues/27
Связано с задачей список мест https://github.com/WillyTeam/willy/issues/19
Связано с задачей

**Comment by Philat** [comment]
пока что есть 5

**Comment by patut** [comment]
Есть 5 анкет, 2 полностью заполненные, соответственно 2 тестирования.
