### ISSUE TITLE
На реальных девасах вылетает программа (в рандомные моменты)

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#3]
Во время работы программы, программа может закрыться и постоянно закрываться не открываясь и даже не давая выбрать маршрут

**Comment by patut** [comment]
пока что пофиксил все баги с вылетом, которые нашел. Проблему закрывать не буду, так как они возможно еще появятся. Я нашел типичную ошибку, почему они появляются и понял, как ее иправлять, так что пока это не очень сложно. Проверял на iPad через мобильный интернет
