### ISSUE TITLE
Договорится о радио эфире

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#38]
Программный директор Радио ВОС Роговских Игорь Владимирович 8 499 943 36 01
Отдел по работе с молодежбю Дрожжин Василий Викторович 8 926 609 94 77

**Comment by Philat** [comment]
надо написать Олегу (это Радио)
radio@radiovos.ru
он же возможно блоггер
С Василием на следующей неделе

**Comment by patut** [comment]
Задача дублирует https://github.com/WillyTeam/willy/issues/45
