### ISSUE TITLE
Иногда не загружаются адреса на реальных устройствах

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#4]
Во время загрузки приложения появляется белый экран с пустыми ячейками, потому что адреса не успевают попадать в таблицу до выгрузки ее на экран

**Comment by patut** [comment]
https://drive.google.com/drive/#folders/0B75a4hhDNsEVVEZTUlNqYU84U1E/0B75a4hhDNsEVUHAzMXNiZVBsaUk/0B2cN1ZH8gt52fktTNC1NaGpXTzlhN3Y2dkpqaDlaSG1pTkI1MF83WlJQSFVTa1FQck9jSWM

Добавил проверку интернет-соединения перед отправкой запроса, но пока все равно есть случаи с зшрузкой пустой таблицы

**Comment by patut** [comment]
Исправил, работает следующим образом: появляется предупреждение об отсутствии интернет-соединения, затем пользователь возвращается на начальный экран.

https://drive.google.com/open?id=0B2cN1ZH8gt52eHJWaEcyaFI0OFE&authuser=0
