### ISSUE TITLE
Организовать список встреч с ЦА для тестирования

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#40]
Сергей из втемноте +3
Культурный центр +4
Логос (Николай который играет носом в сабвей) + ?

**Comment by patut** [comment]
Еще +3 из КЦ (с моего первого захода). Сегодня в 5 встречаюсь с одним

**Comment by patut** [comment]
Сделано, теперь надо дополнять
https://docs.google.com/spreadsheets/d/1VKZRlEz9-mj1elERL_JHcF1ylDF8iF5hbuwZ3wSWAPI/edit#gid=0
