### ISSUE TITLE
Радиоэфир

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#45]
Написать Олегу radio@radiovos.ru насчет эфира на радио ВОС

**Comment by patut** [comment]
отписал Олегу, встреча будет на след неделе.

**Comment by patut** [comment]
Программный директор Радио ВОС Роговских Игорь Владимирович 8 499 943 36 01
Отдел по работе с молодежбю Дрожжин Василий Викторович 8 926 609 94 77

**Comment by patut** [comment]
надо написать Олегу (это Радио)
radio@radiovos.ru
он же возможно блоггер
С Василием на следующей неделе

**Comment by patut** [comment]
позвонил, вечером он ответит на имейл.
