### ISSUE TITLE
Тестирование с Василием

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#46]
Василий на следующей неделе 

Контакты
Программный директор Радио ВОС Роговских Игорь Владимирович 8 499 943 36 01
Отдел по работе с молодежбю Дрожжин Василий Викторович 8 926 609 94 77

**Comment by patut** [comment]
Договорились предварительно на понедельник после работы, завтра созвон

**Comment by patut** [comment]
Протестировал, надо перенести результаты интервью в модель.

**Comment by patut** [comment]
Встретился, результаты занес в таблицу
