### ISSUE TITLE
Нагуглись цены на вентеляторы

### ISSUE THREAD

**Issue by patut** [WillyTeam/willy#51]
Нагуглись цены на вентеляторы. Фольга (2 рулона) и тряпки (как простынь).

**Comment by patut** [comment]
http://market.yandex.ru/catalog/90565/list?exc=1&how=dpop

Цены колеблятся от 800 рублей до 4000. Хороший вентелятор можно взять за 1350 (оценка 4 из 5). Основной его недостаток - неэстетично выглядит, но чем он отличается от вентеляторов зв 3000 помимо этого, я так и не понял. Мощность у тех и у тех - 60 Вт. Можно взять модель за 1600 (оценка 4.5 из 5), он помощнее - 90 Вт.

**Comment by Philat** [comment]
давай возьмем два за 1350 пусть они и уродские
кинь ссылку сюда
чуть попозже купим

15 апреля 2015 г., 15:02 пользователь patut notifications@github.com
написал:

**Comment by patut** [comment]
http://www.10i.ru/product/Ventilyator_napolnyj_Rolsen_RSF-1650RT_Bronze_275211.html?utm_source=Yandex_Market&utm_medium=cpc&utm_campaign=main_22&utm_content=ventilyator+napolnyy+Rolsen+Rsf+1650Rt+Bronze&_openstat=bWFya2V0LnlhbmRleC5ydTvQktC10L3RgtC40LvRj9GC0L7RgCDQvdCw0L_QvtC70YzQvdGL0LkgUm9sc2VuIFJzZi0xNjUwUnQgQnJvbnplO2dmUlJYdndsaWg3U0VPRUpkN1N2S1E7

Ссылка на товар
