### ISSUE TITLE
Написать текст для радиоэфира

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#54]
продумать всю речовку чтобы не болтал лишнего и был няшей

**Comment by patut** [comment]
О нас:
Мы - аудио голосового навигатора для слепых и слабовидящих. Мы хотим помочь им социализироваться в городе путем решения их проблемы: самостоятельное передвижение в городе. Наша команда состоит из двух человек: разработчик сайтов и дизайнер Филатов Сергей и разработчик мобильных приложений Патутинский Федор. Команда уже успела реализовать несколько интересных проектов, в частности, мы сделали мобильное приложение в университете, которое помогает организовывать дополнительные занятия студентам.

О работе приложения: 
Наш продукт - мобильное приложение для смартфонов. На данный момент есть прототип для iOS устройств, также мы планируем выпустить версии для Android и Windows Phone. Его работа основана на технологии GPS. Приложение выдает аудио подсказки в важные моменты движения пользователя, сообщая ему время, расстояние и другие параметры маршрута. В приложении возможно выбрать желаемое место назначения без печатного ввода точного адреса: пользователь просто выбирает категорию места, которую он хочет попасть (магазин, кафе, гос учреждение), программа выдает ему список ближайших адресов и далее пользователь выбирает точку назначения. Далее программа строит маршрут и оглашает пользователю аудио подсказки, в каком направлении необходимо осуществлять движение.

О тестировании:
Сейчас проект находится на этапе тестирования и доработки. Тестирование проводится как с тотально слепыми, так и со слабовидящими. После каждого этапа тестирования приложение дорабатывается и выпускается обновление. 

О названии
Мы назвали наш проект в честь моего пса, Willy.

Мы хотим помочь им социализироваться в городе путем решения их проблемы: самостоятельное передвижение в городе.
Цель программы - помочь слепым и слабовидящим людям ориентироваться в городе и самостоятельно добираться до необходимого места
09:15:57  
или 
программа помогает слепым и слабовидящим людям ориентироваться в городе и добираться до места назначения с помошью оглашения подробных аудио подсказок
ну то есть как-то более по человечески написать а не так канцелярски
