### ISSUE TITLE
правки

### ISSUE THREAD

**Issue by Philat** [WillyTeam/willy#57]
Включать VoiceOver при запуске приложения. Не знаю, как сделать, в инете не нашел.
Не озвучивает при переходе на список после выбора категорий - сделано.
Оглашение всего маршрута по чекпойнтам - сделано.
Запад и стороны света заменить на адекватные право лево - 30 минут.
Сложное - озвучивать улицы по вектору движения, а не единственную ближайшую - 8 часов.
маршрут должен быть пешеходным и до выхода метро а не до центра станции - час на исследование и 4 часа на реализацию.
Места вокруг вас. Сделать через строчку места вокруг вас. 2 часа.
Ориентиры на маршруте. - 7 часов.
Создать второй массив с менее полными инструкциями - 1 час. 
Вы сбились с маршрута. Сейчас мы строим новый маршрут. - 3 часа.
Сколько осталось метров до следующей инструкции. Добавить к местам вокруг вас. - 2 часа
Сложное - перейти дорогу. 1 день
Фоновый режим - несложно. 2 часа

Таблица:
Кусок маршрута, где я

Попадать на инструкцию не пролистывая. Уже есть, надо будет доработать

Узнать про то, можно ли выкинуть карту гугл на таббар. Не самое сложное. - 1 час

«Поверните налево на 45% в сторону улицы Осенний бульвар, ТЦ Вегас (локально конечная точка отрезка пути). пройдите прямо 500 м. по пути вы пройдете Якиторию, Секонд-хенд, Аптеку. на 100 м перейдите дорогу.»

**Comment by patut** [comment]
Включать VoiceOver при запуске приложения - пока хз, как сделать. Вчера копался долго в инете.
Не озвучивает при переходе на список после выбора категорий - исправил
Оглашение всего маршрута по чекпойнтам  - добавил как первую строку.

**Comment by patut** [comment]
Запад и стороны света заменить на адекватные право лево - 30 минут. - сделано
Места вокруг вас. Сделать через строчку места вокруг вас. 2 часа. - сделано

**Comment by patut** [comment]
Задача: добавить в ячейку перед "Вокруг вас..." текст "До поворота осталось х метров". Если пользователь сбивается с маршрута, то менять сообщение "До поворота осталось х метров" на "Вы сбились с маршрута.".

**Comment by patut** [comment]
Места вокруг вас. Сделать через строчку места вокруг вас. 2 часа. - сделано
Задача: добавить в ячейку перед "Вокруг вас..." текст "До поворота осталось х метров". Если пользователь сбивается с маршрута, то менять сообщение "До поворота осталось х метров" на "Вы сбились с маршрута.". - сделано

**Comment by patut** [comment]
Ориентиры на маршруте - сделано
Сколько осталось метров до следующей инструкции. Добавить к местам вокруг вас. - 2 часа - сделано
Фоновый режим - несложно. 2 часа - сделано
Создать второй массив с менее полными инструкциями - 1 час.  - реализовано несколько по-другому, но цель - оглашение общего маршрута с менее подробными инструкциями выполнена

**Comment by patut** [comment]
ТЦ Вегас (локально конечная точка отрезка пути) - добавлено

**Comment by patut** [comment]
Все, что смог, то добавил
